name: Pipeline

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Get Previous tag
        id: previousTag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"
        with:
          fallback: 1.0.0 # Optional fallback tag to use when no tag can be found

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          file: docs.Dockerfile
          push: true
          tags: |
            aysnine/frps-default-docker:${{ steps.previousTag.outputs.tag }}
            aysnine/frps-default-docker:latest
